name: .NET

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Boba.PasswordManager
      run: dotnet build Boba/Boba.PasswordManager/Boba.PasswordManager.csproj --no-restore
    - name: Build Boba.CLI
      run: dotnet build Boba/Boba.CLI/Boba.CLI.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
