name: Build

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build Boba.PasswordManager
      run: dotnet build ${{github.workspace}}/Boba.PasswordManager/Boba.PasswordManager.csproj --no-restore

    - name: Build Boba.CLI
      run: dotnet build ${{github.workspace}}/Boba.CLI/Boba.CLI.csproj --no-restore

    - name: Build Boba.Desktop
      run: dotnet build ${{github.workspace}}/Boba.Desktop/Boba.Desktop.csproj --no-restore

    - name: Run Boba.PasswordManagerTests
      run: dotnet test ${{github.workspace}}/Boba.PasswordManagerUnitTests/Boba.PasswordManagerUnitTests.csproj --verbosity normal
